### ISSUE TITLE
Channel Launch

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/smspoh#1]
- [x] Code Review
- [x] Add @tintnaingwinn as repo admin
- [x] Add @tintnaingwinn to github org
- [x] Add to website
- [x] Create packagist package
- [x] Travis
- [x] Style CI
- [x] Scrutinizer 
- [x] Add badges

**Comment by atymic** [comment]
Website PR: https://github.com/laravel-notification-channels/website/pull/12

**Comment by atymic** [comment]
Once you've merged i'll set up the rest of the tools :)

**Comment by atymic** [comment]
All services added :)
Let me know when you tag the first release and i'll merge the website PR

**Comment by tintnaingwinn** [comment]
I have already release.

**Comment by atymic** [comment]
Sweet, live on the website as well :)
https://laravel-notification-channels.com/smspoh

Thanks!
Will close the issue now.
